import type { IntelligentApp, Agent, AgentConfig, PromptArtifact, RunRecord, SchemaViolation, Tool } from "./types"

// Placeholder data following typed placeholders pattern (no hardcoding mock data)

export const getIntelligentApps = (): IntelligentApp[] => [
  {
    id: "app-1",
    name: "Trade Analysis Pipeline",
    version: "2.1.0",
    agentCount: 4,
    status: "Deployed",
    lastUpdated: "2024-01-15T10:30:00Z",
    description: "Multi-agent pipeline for trade analysis and reporting",
  },
  {
    id: "app-2",
    name: "Document Processor",
    version: "1.3.2",
    agentCount: 3,
    status: "Deployed",
    lastUpdated: "2024-01-14T15:45:00Z",
    description: "Extracts and transforms financial documents",
  },
  {
    id: "app-3",
    name: "Risk Assessment Suite",
    version: "0.9.0",
    agentCount: 5,
    status: "Draft",
    lastUpdated: "2024-01-13T09:20:00Z",
    description: "Comprehensive risk analysis orchestration",
  },
  {
    id: "app-4",
    name: "Client Onboarding Flow",
    version: "1.0.0",
    agentCount: 2,
    status: "Archived",
    lastUpdated: "2024-01-10T12:00:00Z",
    description: "Automated client onboarding workflow",
  },
]

export const getAgentsForApp = (appId: string): Agent[] => [
  {
    id: "agent-1",
    name: "Data Extractor",
    type: "Extractor",
    typeCategory: "Core Intelligence",
    category: "Data Processing",
    configVersion: "1.2.0",
    toolsEnabled: ["pdf-parser", "ocr-engine"],
    description: "Extracts structured data from unstructured sources",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "agent-2",
    name: "Field Mapper",
    type: "Mapper",
    typeCategory: "Function",
    category: "Data Processing",
    configVersion: "1.1.0",
    toolsEnabled: ["schema-validator"],
    description: "Maps extracted fields to target schema",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "agent-3",
    name: "Risk Analyzer",
    type: "Analysis",
    typeCategory: "Industry",
    category: "Finance",
    configVersion: "2.0.0",
    toolsEnabled: ["risk-calculator", "market-data-api"],
    description: "Analyzes risk factors and generates scores",
    isExistingAgent: false,
    hasAIBuilder: true,
  },
  {
    id: "agent-4",
    name: "Report Generator",
    type: "Summarizer",
    typeCategory: "Function",
    category: "Document Analysis",
    configVersion: "1.0.5",
    toolsEnabled: ["template-engine"],
    description: "Generates summary reports from analysis results",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
]

export const getAgentLibrary = (): Agent[] => [
  {
    id: "lib-agent-1",
    name: "Enterprise RAG Agent",
    type: "Extractor",
    typeCategory: "Core Intelligence",
    category: "Knowledge & RAG",
    configVersion: "2.0.0",
    toolsEnabled: ["vector-search", "document-loader", "embeddings"],
    description: "Advanced retrieval-augmented generation for enterprise knowledge bases",
    isExistingAgent: true,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-2",
    name: "Semantic Search Agent",
    type: "Extractor",
    typeCategory: "Core Intelligence",
    category: "Knowledge & RAG",
    configVersion: "1.5.0",
    toolsEnabled: ["vector-search", "reranker"],
    description: "Intelligent semantic search across documents and data sources",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-3",
    name: "Planning Agent",
    type: "Analysis",
    typeCategory: "Core Intelligence",
    category: "Reasoning & Planning",
    configVersion: "1.2.0",
    toolsEnabled: ["task-planner", "goal-tracker"],
    description: "Multi-step planning and task decomposition agent",
    isExistingAgent: false,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-4",
    name: "Credit Memo Agent",
    type: "Analysis",
    typeCategory: "Industry",
    category: "Banking",
    configVersion: "3.0.0",
    toolsEnabled: ["credit-calculator", "risk-scorer", "compliance-checker"],
    description: "Automated credit memo generation and analysis for banking",
    isExistingAgent: true,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-5",
    name: "Loan Underwriting Agent",
    type: "Analysis",
    typeCategory: "Industry",
    category: "Banking",
    configVersion: "2.1.0",
    toolsEnabled: ["underwriting-engine", "document-verifier"],
    description: "AI-powered loan underwriting and document verification",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-6",
    name: "Portfolio Optimizer",
    type: "Analysis",
    typeCategory: "Industry",
    category: "Finance",
    configVersion: "1.8.0",
    toolsEnabled: ["optimization-engine", "market-data-api", "risk-calculator"],
    description: "Portfolio optimization and rebalancing recommendations",
    isExistingAgent: false,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-7",
    name: "Trade Reconciliation Agent",
    type: "Mapper",
    typeCategory: "Industry",
    category: "Finance",
    configVersion: "2.0.0",
    toolsEnabled: ["matcher", "discrepancy-detector"],
    description: "Automated trade matching and reconciliation",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-8",
    name: "Claims Processing Agent",
    type: "Extractor",
    typeCategory: "Industry",
    category: "Insurance",
    configVersion: "1.5.0",
    toolsEnabled: ["ocr-engine", "claim-validator", "fraud-detector"],
    description: "End-to-end insurance claims processing and validation",
    isExistingAgent: true,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-9",
    name: "Policy Analyzer",
    type: "Analysis",
    typeCategory: "Industry",
    category: "Insurance",
    configVersion: "1.2.0",
    toolsEnabled: ["policy-parser", "coverage-analyzer"],
    description: "Insurance policy analysis and coverage extraction",
    isExistingAgent: false,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-10",
    name: "Document Parser",
    type: "Extractor",
    typeCategory: "Function",
    category: "Document Analysis",
    configVersion: "2.5.0",
    toolsEnabled: ["pdf-parser", "ocr-engine", "table-extractor"],
    description: "Universal document parsing and data extraction",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-11",
    name: "Contract Analyzer",
    type: "Analysis",
    typeCategory: "Function",
    category: "Document Analysis",
    configVersion: "1.8.0",
    toolsEnabled: ["clause-extractor", "risk-identifier"],
    description: "Legal contract analysis and clause extraction",
    isExistingAgent: true,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-12",
    name: "ETL Orchestrator",
    type: "Mapper",
    typeCategory: "Function",
    category: "Data Processing",
    configVersion: "2.0.0",
    toolsEnabled: ["data-transformer", "schema-validator", "loader"],
    description: "Data pipeline orchestration and transformation",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-13",
    name: "Data Quality Agent",
    type: "Analysis",
    typeCategory: "Function",
    category: "Data Processing",
    configVersion: "1.3.0",
    toolsEnabled: ["validator", "anomaly-detector", "profiler"],
    description: "Data quality assessment and anomaly detection",
    isExistingAgent: false,
    hasAIBuilder: true,
  },
  {
    id: "lib-agent-14",
    name: "Email Composer",
    type: "Summarizer",
    typeCategory: "Function",
    category: "Communication",
    configVersion: "1.1.0",
    toolsEnabled: ["template-engine", "tone-analyzer"],
    description: "AI-powered email composition and response generation",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
  {
    id: "lib-agent-15",
    name: "Meeting Summarizer",
    type: "Summarizer",
    typeCategory: "Function",
    category: "Communication",
    configVersion: "1.5.0",
    toolsEnabled: ["transcript-parser", "action-extractor"],
    description: "Meeting transcription and action item extraction",
    isExistingAgent: true,
    hasAIBuilder: false,
  },
]

export const getAgentConfig = (agentId: string): AgentConfig => ({
  id: agentId,
  name: "Data Extractor",
  type: "Extractor",
  version: "1.2.0",
  model: {
    provider: "OpenAI",
    name: "gpt-4-turbo",
    temperature: 0.1,
    maxTokens: 4096,
  },
  prompts: {
    systemPromptUri: "mlflow://prompts/extractor/system/v1.2",
    taskPromptUri: "mlflow://prompts/extractor/task/v1.2",
  },
  schemas: {
    inputSchemaUri: "mlflow://schemas/extractor/input/v1.0",
    outputSchemaUri: "mlflow://schemas/extractor/output/v1.0",
  },
  tools: getAvailableTools(),
  memory: {
    enabled: true,
    namespace: "extractor-memory",
    retentionPolicy: "30d",
  },
})

export const getAvailableTools = (): Tool[] => [
  { id: "tool-1", name: "pdf-parser", enabled: true, deterministic: true, hasSideEffects: false },
  { id: "tool-2", name: "ocr-engine", enabled: true, deterministic: false, hasSideEffects: false },
  { id: "tool-3", name: "schema-validator", enabled: false, deterministic: true, hasSideEffects: false },
  { id: "tool-4", name: "risk-calculator", enabled: false, deterministic: true, hasSideEffects: false },
  { id: "tool-5", name: "market-data-api", enabled: false, deterministic: false, hasSideEffects: true },
  { id: "tool-6", name: "template-engine", enabled: false, deterministic: true, hasSideEffects: false },
  { id: "tool-7", name: "email-sender", enabled: false, deterministic: false, hasSideEffects: true },
  { id: "tool-8", name: "database-writer", enabled: false, deterministic: false, hasSideEffects: true },
]

export const getPromptArtifacts = (): PromptArtifact[] => [
  {
    id: "prompt-1",
    name: "Extractor System Prompt",
    type: "system",
    version: "1.2.0",
    lastUpdated: "2024-01-15T10:30:00Z",
    content: "You are a specialized data extraction agent...",
  },
  {
    id: "prompt-2",
    name: "Extractor Task Prompt",
    type: "task",
    version: "1.2.0",
    lastUpdated: "2024-01-15T10:30:00Z",
    content: "Extract the following fields from the document...",
  },
  {
    id: "prompt-3",
    name: "Mapper System Prompt",
    type: "system",
    version: "1.1.0",
    lastUpdated: "2024-01-14T15:45:00Z",
    content: "You are a field mapping specialist...",
  },
  {
    id: "prompt-4",
    name: "Input Schema",
    type: "schema",
    version: "1.0.0",
    lastUpdated: "2024-01-13T09:20:00Z",
    content: '{ "type": "object", "properties": {...} }',
  },
  {
    id: "prompt-5",
    name: "Output Schema",
    type: "schema",
    version: "1.0.0",
    lastUpdated: "2024-01-13T09:20:00Z",
    content: '{ "type": "object", "properties": {...} }',
  },
]

export const getRunRecords = (): RunRecord[] => [
  {
    id: "run-1",
    timestamp: "2024-01-15T10:35:00Z",
    agentName: "Data Extractor",
    appName: "Trade Analysis Pipeline",
    status: "Success",
    latency: 1250,
  },
  {
    id: "run-2",
    timestamp: "2024-01-15T10:34:00Z",
    agentName: "Field Mapper",
    appName: "Trade Analysis Pipeline",
    status: "Success",
    latency: 450,
  },
  {
    id: "run-3",
    timestamp: "2024-01-15T10:33:00Z",
    agentName: "Risk Analyzer",
    appName: "Trade Analysis Pipeline",
    status: "Failed",
    latency: 3200,
  },
  {
    id: "run-4",
    timestamp: "2024-01-15T10:32:00Z",
    agentName: "Report Generator",
    appName: "Document Processor",
    status: "Success",
    latency: 890,
  },
  {
    id: "run-5",
    timestamp: "2024-01-15T10:31:00Z",
    agentName: "Data Extractor",
    appName: "Document Processor",
    status: "Running",
    latency: 0,
  },
]

export const getSchemaViolations = (): SchemaViolation[] => [
  {
    id: "violation-1",
    timestamp: "2024-01-15T10:33:00Z",
    agentName: "Risk Analyzer",
    expected: '{ "riskScore": number, "confidence": number }',
    actual: '{ "riskScore": "high", "confidence": 0.95 }',
  },
  {
    id: "violation-2",
    timestamp: "2024-01-14T15:20:00Z",
    agentName: "Field Mapper",
    expected: '{ "mappedFields": array }',
    actual: '{ "mappedFields": null }',
  },
]

export const getConfigTemplates = () => [
  { id: "template-1", name: "Default Extractor Config", type: "Extractor" },
  { id: "template-2", name: "Default Mapper Config", type: "Mapper" },
  { id: "template-3", name: "Default Analysis Config", type: "Analysis" },
  { id: "template-4", name: "Default Summarizer Config", type: "Summarizer" },
]
